main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  # PlantS
  path('plants/', views.plants_index, name='index'),
  path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
  path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name="plants_update"),
  path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name="plants_delete"),
  path('plants/<int:plant_id>/', views.plants_detail, name="detail"),
  # Watering
  path('plants/<int:plant_id>/add_watering', views.add_watering, name='add_watering'),
  # Photos
  path('plants/<int:plant_id>/plant_photo/', views.add_photo, name='add_photo'),
  # Fertilizer
  path('fertilizers/', views.FertilizerList.as_view(), name="fertilizers_index"),
  path('fertilizers/<int:pk>/', views.FertilizerDetail.as_view(), name="fertilizers_detail"),
  path('fertilizers/create/', views.FertilizerCreate.as_view(), name="fertilizers_create"),
  path('fertilizers/<int:pk>/update/', views.FertilizerUpdate.as_view(), name="fertilizers_update"),
  path('fertilizers/<int:pk>/delete/', views.FertilizerDelete.as_view(), name="fertilizers_delete"),
  path('plants/<int:plant_id>/assoc_fertilizer/<int:fertilizer_id>/', views.assoc_fertilizer, name='assoc_fertilizer'),
  path('plants/<int:plant_id>/remove_fertilizer/<int:fertilizer_id>/', views.remove_fertilizer, name='remove_fertilizer'),
  # Account
  path('accounts/signup/', views.signup, name='signup'),
]

plantparenthood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

# -------------------- FERTILIZER MODEL  -------------------- #
class Fertilizer(models.Model):
  brand_name = models.CharField(max_length=100)
  source_type = models.CharField(max_length=100)
  nutrient_balance = models.CharField(
    max_length=8,
    help_text= "Enter as XX:XX:XX or XX-XX-XX"
  )
  rec_freq = models.CharField(
    'Recommended Frequency',
    max_length=100,
    help_text= "Check packaging instructions"
  )

  def get_absolute_url(self):
    return reverse('fertilizers_detail', kwargs={'pk': self.id})

# -------------------- PLANT -------------------- #

DIFFICULTIES = (
  ('E', 'Easy'),
  ('M', 'Medium'),
  ('H', 'Hard'),
)

LIGHT = (
  ('L', 'Low Light'),
  ('I', 'Bright Indirect'),
  ('D', 'Direct')
)

class Plant(models.Model):
  nickname = models.CharField(max_length=100)
  common_name = models.CharField(max_length=100)
  scientific_name = models.CharField(max_length=100)
  care_difficulty = models.CharField(
    max_length=1,
    choices=DIFFICULTIES,
    default=DIFFICULTIES[0][0]
  )

  light_requirement = models.CharField(
    max_length=1,
    choices=LIGHT,
    default=LIGHT[1][0]
  )

  water_interval = models.IntegerField(
    help_text= "(Enter days between waterings)"
  )

  fertilizers = models.ManyToManyField(Fertilizer)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def get_absolute_url(self):
    return reverse('detail', kwargs={'plant_id': self.id})


  def __str__(self):
    return f'{self.common_name}'

# -------------------- WATERING -------------------- #

class Watering(models.Model): 
  date = models.DateField()
  plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

# -------------------- PHOTO -------------------- #
class Photo(models.Model):
  url = models.CharField(max_length=200)
  plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

  def __str__(self):
    return f'Photo for plant_id: {self.plant_id} at {self.url}.'

main_app/forms.py
from django import forms

from django.forms import ModelForm    
from django.forms.widgets import DateInput

from .models import Watering

class DateInput(forms.DateInput):
    input_type = 'date'

class WateringForm(ModelForm):
  class Meta:
    model = Watering
    fields = ['date']
    widgets = {
      'date': DateInput(attrs={'type': 'date'}),
    }

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import WateringForm

from .models import Plant, Fertilizer, Photo

import uuid
import boto3

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'plantparenthood22'

# VIEWS


def home(request):
  return render(request, 'home.html')


def about(request):
  return render(request, 'about.html')

# ---------------------- PLANTS ----------------------#


@login_required
def plants_index(request):
    plants = Plant.objects.filter(user=request.user)
    return render(request, 'plants/index.html', {'plants': plants})


@login_required
def plants_detail(request, plant_id):
    plant = Plant.objects.get(id=plant_id)
    available_fertilizers = Fertilizer.objects.exclude(
        id__in=plant.fertilizers.all().values_list('id'))
    watering_form = WateringForm()
    return render(request, 'plants/detail.html', {'plant': plant, 'watering_form': watering_form, 'fertilizers': available_fertilizers})


class PlantCreate(LoginRequiredMixin, CreateView):
    model = Plant
    fields = ['nickname', 'common_name', 'scientific_name',
              'care_difficulty', 'light_requirement', 'water_interval']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PlantUpdate(LoginRequiredMixin, UpdateView):
    model = Plant
    fields = ['nickname', 'common_name', 'scientific_name',
              'care_difficulty', 'light_requirement', 'water_interval']


class PlantDelete(LoginRequiredMixin, DeleteView):
    model = Plant
    success_url = '/plants/'

# ---------------------- WATERING ---------------------- #


@login_required
def add_watering(request, plant_id):
    form = WateringForm(request.POST)
    if form.is_valid():
        new_watering = form.save(commit=False)
        new_watering.plant_id = plant_id
        new_watering.save()
    return redirect('detail', plant_id=plant_id)


# ---------------------- LOGIN/SIGNUP ---------------------- #
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form, 'error_message': error_message})


# ---------------------- FERTILIZER ---------------------- #
class FertilizerList(ListView):
    model = Fertilizer


class FertilizerDetail(DetailView):
    model = Fertilizer


class FertilizerCreate(CreateView):
    model = Fertilizer
    fields = "__all__"


class FertilizerUpdate(UpdateView):
    model = Fertilizer
    fields = "__all__"


class FertilizerDelete(DeleteView):
    model = Fertilizer
    success_url = "/fertilizers/"


@login_required
def assoc_fertilizer(request, plant_id, fertilizer_id):
    plant = Plant.objects.get(id=plant_id)
    plant.fertilizers.add(fertilizer_id)
    return redirect('detail', plant_id=plant_id)


@login_required
def remove_fertilizer(request, plant_id, fertilizer_id):
    plant = Plant.objects.get(id=plant_id)
    plant.fertilizers.remove(fertilizer_id)
    return redirect('detail', plant_id=plant_id)


# ---------------------- PHOTOS ---------------------- #
@login_required
def add_photo(request, plant_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]

        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            Photo.objects.create(url=url, plant_id=plant_id)
        except:
            print('An error occured uploading file to S3')
    return redirect('detail', plant_id=plant_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<div class="about-container text-center">
  <h1>About Us</h1>
  <div class="row">
    <div class="col-5">
      <h4>What We Do</h4>
      <p>
        It's hard to keep plants alive when life gets in the way. Plant parents everywhere can now look to Plant Parenthood to help them keep track of essential care such as waterings and feedings.<br /><br />
        Plant Parenthood allows users to add plants to their list, keep track of when they last watered, and what fertilizers were used.
      </p>
    </div>
    <div class="col-7">
      <img src="https://images.squarespace-cdn.com/content/v1/550b57f0e4b03338e0474a39/1639165327624-UH68EOTUC39Y7RAF6J52/STUMP+PLANTS+SITE+MAIN_006.jpg" class="img-fluid" alt="Plant Care" />
    </div>
  </div>
  <hr />
  
  <div class="row">
    <div class="col-5">
      <h4>Our Team</h4>
      <p></p>
    </div>
    <div class="col-7">
      <img src="https://i.imgur.com/NDfzdPW.png" class="img-fluid" alt="Team Photo" />
    </div>
  </div>
  <hr />
</div>
<hr />

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@600&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/9e06729fec.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>

  <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #187B4D;">
    <span class="navbar-brand mb-0 h1">
      <img src="https://i.imgur.com/vCVknyq.png" width="32" height="32" class="d-inline-block align-top" alt="">
      Plant Parenthood
    </span>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav" style="margin-left: auto;">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>

        {% if user.is_authenticated %}

        <li class="nav-item">
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Plants</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{% url 'index' %}">My Plants</a></li>
                <li><a class="dropdown-item" href="{% url 'plants_create' %}">Add a Plant</a></li>
            </ul>
          </div>
        </li>

        <li class="nav-item">
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Supplementals</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{% url 'fertilizers_index' %}">View Fertilizers</a></li>
                <li><a class="dropdown-item" href="{% url 'fertilizers_create' %}">Add Fertilizer</a></li>
            </ul>
          </div>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>
        
        {% else %}

        <li class="nav-item"><a class="nav-link active" aria-current="true" href="{% url 'signup' %}">Sign Up</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="true" href="{% url 'login' %}">Log In</a></li>
        
        {% endif %}
      </ul>
    </div>
  </nav>

    <main>
        {% block content %}


        {% endblock %}
    </main>

</body>
</html>

main_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@600&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
  <main>
    <div class="main-page">
      <div class="all">
        <div class="title">
          <h1 class="base-header-plant">Plant</h1>
            <h1 class="base-header-parenthood">Parenthood</h1>
        </div>
        
        <div class="animation">
          <div class="about">
            <div class="wrapper">

              <div class="static-txt">Plant care, made</div>
              <ul class ="dynamic-txts">
                <li><span>easy.</span></li>
                <li><span>simple.</span></li>
                <li><span>accessible.</span></li>
                <li><span>fun.</span></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
        
      <div class="directory">
        
        <div class="login">
          <a href="{% url 'login' %}">
            <button class="button-50" role="button">Log In</button>
          </a>
        </div>
        
        <div class="signup">
          <a href="{% url 'signup' %}">
              <button class="button-50" role="button">Sign Up</button>
          </a>
        </div>
        
        <div class="monstera-one">
          <img src="https://i.imgur.com/vCVknyq.png">
        </div>
        
        <div class="monstera-two">
          <img src="https://i.imgur.com/vCVknyq.png">
        </div>
        
    </div>

  
  </main>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>

</body>
</html>

main_app/templates/main_app/fertilizer_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="text-center">
  <h1>Delete Fertilizer</h1>
  <h4>Are you sure you want to delete <span class="green-text">{{ object.brand_name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!">
    <a href="{% url 'fertilizers_detail' object.id %}" class="modify">Cancel</a>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/fertilizer_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="text-center">
  <h1>Fertilizer Details</h1>
  <div class="container">
    <h2 class="green-text">{{ fertilizer.brand_name }}</h2>
    <p>Source Type: {{ fertilizer.source_type }}</p>
    <p>Nutrient Balance: {{ fertilizer.nutrient_balance }}</p>
    <p>Reccommended Frequency: {{ fertilizer.rec_freq }}</p>
    <div>
      <a href="{% url 'fertilizers_update' fertilizer.id %}" class="modify">Edit</a>
      <a href="{% url 'fertilizers_delete' fertilizer.id %}" class="modify">Delete</a>
    <div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/fertilizer_form.html
{% extends 'base.html' %}
{% block content %}

  {% if object %}
    <h1 class="text-center">Edit <span class="green-text">{{ object.brand_name }}</span></h1>
  {% else %}
    <h1 class="text-center">Add Fertilizer</h1>
  {% endif %}
  <div class="container">
    <form action="" method="POST">
      {% csrf_token %}
      <table>{{ form.as_table }}</table>
      <input type="submit" value="Submit" />
    </form>
  </div>

{% endblock %}

main_app/templates/main_app/fertilizer_list.html
{% extends 'base.html' %}
{% block content %}

<div class="text-center">
  <h1>Fertilizer List</h1>
  <div class="list-container">
  {% for fertilizer in fertilizer_list %}
    <a href="{% url 'fertilizers_detail' fertilizer.id %}">
      <div class="list">
        <h5 class="green-text">{{ fertilizer.brand_name }}</h5>
        <p>Nutrient Balance: {{ fertilizer.nutrient_balance }}</p>
      </div>
    </a>
  {% endfor %}
  </div>
</div>

{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="text-center">
  <h1>Delete Plant</h1>

  <h4>Are you sure you want to delete <span class="green-text">{{ object.nickname }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!">
    <a href="{% url 'detail' object.id %}" class="modify">Cancel</a>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
  <h1 class="text-center">Edit <span class="green-text">{{ object.nickname }}</span></h1>
{% else %}
  <h1 class="text-center">Add a Plant</h1>
{% endif %}
  <div class="container">
    <form action="" method="POST">
      {% csrf_token %}
      <table>{{ form.as_table }}</table>
      <input type="submit" value="Submit" />
    </form>
  <div>

{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% block content %}

<!----------- DETAILS ----------->
<h1 class="text-center">Plant Details</h1>
<div class="detail-container">
  <h2 class="green-text">{{ plant.nickname }}</h2>
  <div class="plant-info">
    {% for photo in plant.photo_set.all %}
      <img src="{{photo.url}}" class="detail-image" alt="Plant Photo">
    {% empty %}
      <img src="https://imgur.com/16wehxA.png" class="detail-image" alt="No Photo Uploaded">
    {% endfor %}
    <form action="{% url 'add_photo' plant.id %}" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <input type="file" name="photo-file"><br>
      <input type="submit" value="Upload Photo">
    </form>
  </div>

  <div class="plant-info">
    <div class="icon1">
      <i class="fa-regular fa-pen-to-square fa-bounce fa-xl icon"></i>
    </div>
    <br>
    <p>Common Name: {{ plant.common_name }}</p>
    <p>Scientific Name: {{ plant.scientific_name }}</p>
    <p>Care Difficulty: {{ plant.get_care_difficulty_display }} </p>
    <p>Light Requirement: {{ plant.get_light_requirement_display }} </p>
    <p>Water Interval: Every {{ plant.water_interval }} days</p>
    <div>
      <a href="{% url 'plants_update' plant.id %}" class="modify">Edit</a>
      <a href="{% url 'plants_delete' plant.id %}" class="modify">Delete</a>
    </div>
  </div>


  <!----------- WATERING ----------->
  <div class="plant-info">
    <div class="icon2">
      <i class="fa-solid fa-droplet fa-bounce fa-xl"></i>
    </div><br>
    <form action="{% url 'add_watering' plant.id %}" method="POST">
      {% csrf_token %}
      {{watering_form.as_p}}
      <input type="submit" value="Add Watering">
    </form>
    <br>
    <table>
      <thead>
        <tr><th><span class="text-decoration-underline">Watering Date</span></th></tr>
      </thead>
      <tbody>
        {% for watering in plant.watering_set.all %}
          <tr><td>{{watering.date}}</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


<!----------- FERTILIZER ----------->
<div class="detail-container">
  <div class="text-center">
    <h3>{{ plant.nickname }}'s Fertilizer</h3>
  {% if plant.fertilizers.count %}
    {% for fertilizer in plant.fertilizers.all %}
      <div class="fertilizer-list">
        <h5 class="green-text">{{ fertilizer.brand_name }}</h5>
        <p>Source Type: {{ fertilizer.source_type }}</p>
        <p>Nutrient Balance: {{ fertilizer.nutrient_balance }}</p>
        <p>Recommended Frequency: {{ fertilizer.rec_freq }}</p>
        <form action="{% url 'remove_fertilizer' plant.id fertilizer.id %}" method="post">
          {% csrf_token %}
          <button type="submit">Remove Fertilizer</button>
        </form>
      </div>
    {% endfor %}
  {% else %}
    <h5>No fertilizers</h5>
  {% endif %}
  </div>

  <div class="text-center">
    <h3>Available Fertilizers</h3>
  {% if fertilizers.count %}
    {% for fertilizer in fertilizers.all %}
    <div class="fertilizer-list">
      <h5 class="green-text">{{ fertilizer.brand_name }}</h5>
      <p>Source Type: {{ fertilizer.source_type }}</p>
      <p>Nutrient Balance: {{ fertilizer.nutrient_balance }}</p>
      <p>Recommended Frequency: {{ fertilizer.rec_freq }}</p>
      <form action="{% url 'assoc_fertilizer' plant.id fertilizer.id %}" method="POST">
        {% csrf_token %}
        <button type="submit">Add Fertilizer</button>
      </form>
    </div>
    {% endfor %}
  {% else %}
    <h5>No More Fertilizers To Add</h5>
  {% endif %}
  </div>
</div>
<br>

{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% block content %}


<div class="text-center">
  <h1>My Plants</h1>

  {% if plants.count %}
    <div class="list-container">
    {% for plant in plants %}
      <a href="{% url 'detail' plant.id %}">
        <div class="list">
          {% for photo in plant.photo_set.all %}
            <img src="{{photo.url}}" class="image" alt="Plant Photo">
          {% empty %}
            <img src="https://imgur.com/16wehxA.png" class="image" alt="No Photo Uploaded">
          {% endfor %}
          <h6>{{ plant.nickname }}</h6>
          <p>Common Name: {{ plant.common_name }}</p>
        </div>
    </a>
    {% endfor %}
    </div>
  {% else %}
    <p>No plants yet. :(</p>
  {% endif %}
</div>

{% endblock %}